Trace requests with opentracing and jaeger
GraphQL-Portal/graphql-portal pull request #123
Opened 2021-02-12 10:14 UTC by haletsky

2021-02-12 10:27 UTC, msadovyi commented
update mw tests, please

2021-02-26 11:35 UTC, germankrause approved these changes

2021-04-14 11:15 UTC, germankrause approved these changes

2021-04-15 19:46 UTC, valcker requested changes

2021-04-15 19:46 UTC, valcker commented on packages/types/src/gateway-schema.json
> +    "tracing": {
Is tracing always on? It should be possible to enable/disable it.

2021-04-15 19:46 UTC, valcker commented on packages/types/src/gateway-schema.json
> +      "properties": {
Today we support only Jaeger but in future, we might also support Zipkin. Let's add a "tracer name" property or smth like that.

2021-04-15 19:46 UTC, valcker commented on packages/gateway/src/middleware/utils.ts
> +import { Span } from 'opentracing';
We import opentracing but it is included as a dev dependency in package.json. Is it normal?

2021-04-15 19:46 UTC, valcker commented on packages/gateway/src/middleware/assign-request-id.ts
> +  req.context.tracerSpan.setTag('requestId', req.id);
I guess its going to do nothing if tracing is not enabled?

2021-04-16 12:09 UTC, valcker approved these changes

2021-04-16 12:10 UTC, merged