Feature/webhooks
GraphQL-Portal/graphql-portal pull request #292
Opened 2021-04-23 12:06 UTC by msadovyi

2021-04-23 13:00 UTC, valcker approved these changes

2021-04-26 14:24 UTC, germankrause commented on packages/gateway/src/server/router.ts
> +  webhooks.triggerForApi(apiDef.name, WebhookEvents.SCHEMA_CHANGED);
trigger after replacing api in router

2021-04-26 14:25 UTC, germankrause commented on packages/gateway/src/webhooks/Webhooks.ts
> +    [key: string]: {
apiName: string

2021-04-26 14:25 UTC, germankrause commented on packages/gateway/src/webhooks/Webhooks.ts
> +      [key: string]: {
eventName: string

2021-04-26 14:25 UTC, germankrause commented on packages/gateway/src/webhooks/Webhooks.ts
> +        [key: string]: RemoveEventListener; // key equal to url
url: string

2021-04-26 14:27 UTC, germankrause commented on packages/types/src/enum/webhook-events.enum.ts
> +export enum WebhookEvents {
WebhookEvent

2021-04-26 14:28 UTC, germankrause commented on packages/types/src/enum/webhook-events.enum.ts
> +export enum WebhookEvents {
as enum represents one of the value variants

2021-04-26 14:28 UTC, germankrause commented on packages/types/src/enum/index.ts
> +export * from './webhook-events.enum';
webhook-event.enum

2021-04-26 14:29 UTC, germankrause commented on packages/types/src/api-def-schema.json
> +          "url": { "type": "string", "description": "URL that remote API will ping" }
add regex validation for url

2021-04-26 14:36 UTC, germankrause requested changes
update dependencies

2021-04-26 15:07 UTC, germankrause commented on packages/gateway/src/webhooks/Webhooks.ts
> +class Webhooks {
add unit tests

2021-04-26 16:46 UTC, merged